"""refactoring project stucture

Revision ID: b5600c8f337c
Revises: 1663a8d655ee
Create Date: 2023-07-25 15:39:41.663300

"""
from alembic import op  # noqa 401
import sqlalchemy as sa  # noqa 401


# revision identifiers, used by Alembic.
revision = 'b5600c8f337c'
down_revision = '1663a8d655ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
